server:
  port: 7070
  # 请求头最大大小 10MB
  max-http-header-size: 10485760
  servlet:
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: dev
  jackson:
    # 使用24小时的时间格式
    default-property-inclusion: NON_NULL
    # 设置时区为东八区
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  # 枚举类所在包
  type-enums-package: com.kj.enums
  configuration:
    # 开启驼峰命名规则
    map-underscore-to-camel-case: true
    # 枚举映射
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#image:
#  url: http://localhost:8084
#  directory: D:/Projects/ActualProjects/conference/image
image:
  url: http://www.icdske.com
  directory: /home/conference/image