server:
  port: 7070
  # 请求头最大大小 10MB
  max-http-header-size: 10485760
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news_website?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    # 使用24小时的时间格式
    default-property-inclusion: NON_NULL
    # 设置时区为东八区
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  http:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  # 枚举类所在包
  type-enums-package: com.kj.enums
  configuration:
    # 开启驼峰命名规则
    map-underscore-to-camel-case: true
    # 枚举映射
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

